name: Build
permissions:
  contents: write
on:
  workflow_dispatch:
  push:

jobs: 
  build_kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:

      - name: Build Kernel
        run: |
          mkdir -p build/
          touch build/test.k

          
      - name: Publish
        id: release
        uses: softprops/action-gh-release@v2.4.2
        with:
          files: build/*
          name: KERNEL_${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          
          body: |
            **DMXQ-AOSP-KERNEL**:

            - **KERNELSU included (not next)**
            - **Run Number:** ${{ github.run_number }}
      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/*
          compression-level: 0
